# CTF Plugin Configuration

game:
  world_name: "ctf_arena"
  world_type: NORMAL
  world_seed: ""
  attacker_spawn_radius: 50
  defender_spawn_radius: 20
  respawn_cooldown_seconds: 15
  duration_minutes: 30
  attacker_copper_rate_seconds: 5
  defender_copper_rate_seconds: 5
  flag_location_max_attempts: 100
  countdown_seconds: 5

kits:
  axe:
    team: ATTACKERS
    armor:
      helmet: LEATHER_HELMET
      chestplate: LEATHER_CHESTPLATE
      leggings: LEATHER_LEGGINGS
      boots: LEATHER_BOOTS
    items:
      - material: IRON_AXE
        amount: 1
      - material: STONE_PICKAXE
        amount: 1
      - material: STONE_SHOVEL
        amount: 1
      - custom_item: compass
        amount: 1
  sword:
    team: ATTACKERS
    armor:
      helmet: LEATHER_HELMET
      chestplate: LEATHER_CHESTPLATE
      leggings: LEATHER_LEGGINGS
      boots: LEATHER_BOOTS
    items:
      - material: IRON_SWORD
        amount: 1
      - material: SHIELD
        amount: 1
      - material: STONE_PICKAXE
        amount: 1
      - material: STONE_SHOVEL
        amount: 1
      - custom_item: compass
        amount: 1
      - material: BREAD
        amount: 16
  crossbow:
    team: ATTACKERS
    armor:
      helmet: LEATHER_HELMET
      chestplate: LEATHER_CHESTPLATE
      leggings: LEATHER_LEGGINGS
      boots: LEATHER_BOOTS
    items:
      - material: CROSSBOW
        amount: 1
      - material: STONE_PICKAXE
        amount: 1
      - material: STONE_SHOVEL
        amount: 1
      - material: ARROW
        amount: 16
      - custom_item: compass
        amount: 1
      - material: BREAD
        amount: 16

  knight:
    team: DEFENDERS
    armor:
      helmet: DIAMOND_HELMET
      chestplate: DIAMOND_CHESTPLATE
      leggings: DIAMOND_LEGGINGS
      boots: DIAMOND_BOOTS
    items:
      - material: DIAMOND_SWORD
        amount: 1
      - material: SHIELD
        amount: 1
      - material: IRON_AXE
        amount: 1
      - material: IRON_PICKAXE
        amount: 1
      - material: IRON_SHOVEL
        amount: 1
      - material: BREAD
        amount: 16
      - material: COPPER_INGOT
        amount: 20

  archer:
    team: DEFENDERS
    armor:
      helmet: IRON_HELMET
      chestplate: IRON_CHESTPLATE
      leggings: IRON_LEGGINGS
      boots: IRON_BOOTS
    items:
      - material: IRON_SWORD
        amount: 1
      - material: BOW
        amount: 1
        enchantments:
          power: 1
      - material: ARROW
        amount: 64
      - material: IRON_PICKAXE
        amount: 1
      - material: IRON_SHOVEL
        amount: 1
      - material: BREAD
        amount: 16
      - material: COPPER_INGOT
        amount: 20

  builder:
    team: DEFENDERS
    armor:
      helmet: CHAINMAIL_HELMET
      chestplate: CHAINMAIL_CHESTPLATE
      leggings: CHAINMAIL_LEGGINGS
      boots: CHAINMAIL_BOOTS
    items:
      - material: IRON_SWORD
        amount: 1
      - material: DIAMOND_PICKAXE
        amount: 1
      - material: STONE_BRICKS
        amount: 128
      - material: IRON_PICKAXE
        amount: 1
      - material: IRON_SHOVEL
        amount: 1
      - material: BREAD
        amount: 16
      - material: COPPER_INGOT
        amount: 20

shop:
  attackers:
    title: "Attacker Shop"
    trades:
      - input_item: COPPER_INGOT
        input_amount: 1
        output_item: IRON_INGOT
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: GOLD_INGOT
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: DIAMOND
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 8
        output_item: STONE_BRICKS
        output_amount: 64
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: RED_WOOL
        output_amount: 64
      - input_item: COPPER_INGOT
        input_amount: 8
        output_item: GOLDEN_APPLE
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 8
        output_item: instant_tnt
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: fireball
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: BREAD
        output_amount: 16
  defenders:
    title: "Defender Shop"
    trades:
      - input_item: COPPER_INGOT
        input_amount: 1
        output_item: IRON_INGOT
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: GOLD_INGOT
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: DIAMOND
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 8
        output_item: STONE_BRICKS
        output_amount: 64
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: RED_WOOL
        output_amount: 64
      - input_item: COPPER_INGOT
        input_amount: 8
        output_item: GOLDEN_APPLE
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 8
        output_item: instant_tnt
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: fireball
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 32
        output_item: alarm
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: BREAD
        output_amount: 16
