# CTF Plugin Configuration

game:
  world_name: "ctf_arena"
  world_type: NORMAL
  world_seed: ""
  attacker_spawn_radius: 50
  defender_spawn_radius: 20
  attacker_respawn_cooldown_seconds: 15
  defender_respawn_cooldown_seconds: 30
  duration_minutes: 30
  attacker_copper_rate_seconds: 3
  defender_copper_rate_seconds: 2
  flag_location_max_attempts: 100
  countdown_seconds: 5
  sky_platform_height_offset: 5

kits:
  knight:
    armor:
      helmet: IRON_HELMET
      chestplate: IRON_CHESTPLATE
      leggings: IRON_LEGGINGS
      boots: IRON_BOOTS
    items:
      - material: DIAMOND_SWORD
        amount: 1
      - material: SHIELD
        amount: 1
      - material: DIAMOND_AXE
        amount: 1
      - material: WOODEN_PICKAXE
        amount: 1
      - material: BREAD
        amount: 16
      - material: WHITE_WOOL
        amount: 64
      - custom_item: compass
        amount: 1
  archer:
    armor:
      helmet: IRON_HELMET
      chestplate: IRON_CHESTPLATE
      leggings: IRON_LEGGINGS
      boots: IRON_BOOTS
    items:
      - material: IRON_SWORD
        amount: 1
      - material: SHIELD
        amount: 1
      - material: BOW
        amount: 1
        enchantments:
          power: 1
          infinity: 1
      - material: ARROW
        amount: 64
      - material: WOODEN_PICKAXE
        amount: 1
      - material: BREAD
        amount: 16
      - material: WHITE_WOOL
        amount: 64
      - custom_item: compass
        amount: 1

  builder:
    armor:
      helmet: IRON_HELMET
      chestplate: IRON_CHESTPLATE
      leggings: IRON_LEGGINGS
      boots: IRON_BOOTS
    items:
      - material: IRON_SWORD
        amount: 1
      - material: SHIELD
        amount: 1
      - material: IRON_AXE
        amount: 1
      - material: STONE_PICKAXE
        amount: 1
        echantments:
          efficiency: 2
      - material: SHEARS
        amount: 1
      - material: STONE_BRICKS
        amount: 128
      - material: IRON_SHOVEL
        amount: 1
      - material: BREAD
        amount: 16
      - material: WHITE_WOOL
        amount: 64
      - custom_item: compass
        amount: 1
  spear_mace:
    armor:
      helmet: IRON_HELMET
      chestplate: IRON_CHESTPLATE
      leggings: IRON_LEGGINGS
      boots: IRON_BOOTS
    items:
      - material: STONE_SWORD
        amount: 1
      - material: STONE_AXE
        amount: 1
      - material: SHIELD
        amount: 1
      - material: WOODEN_PICKAXE
        amount: 1
      - material: MACE
        enchantments:
          wind_burst: 1
        amount: 1
      - material: DIAMOND_SPEAR
        amount: 1
      - material: BREAD
        amount: 16
      - material: WHITE_WOOL
        amount: 64
      - custom_item: compass
        amount: 1
  mage:
    armor:
      helmet: IRON_HELMET
      chestplate: IRON_CHESTPLATE
      leggings: IRON_LEGGINGS
      boots: IRON_BOOTS
    items:
      - material: STONE_SWORD
        amount: 1
      - material: STONE_AXE
        amount: 1
      - material: SHIELD
        amount: 1
      - material: WOODEN_PICKAXE
        amount: 1
      - material: BREAD
        amount: 16
      - material: WHITE_WOOL
        amount: 64
      - custom_item: compass
        amount: 1
      - material: SPLASH_POTION
        amount: 3
        potion: strong_strength
      - material: SPLASH_POTION
        amount: 3
        potion: harming
      - custom_item: compass
        amount: 1

shop:
  attackers:
    title: "Attacker Shop"
    trades:
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: RED_WOOL
        output_amount: 64
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: END_STONE
        output_amount: 64
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: STONE_BRICK
        output_amount: 64
      - input_item: COPPER_INGOT
        input_amount: 8
        output_item: GOLDEN_APPLE
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 8
        output_item: instant_tnt
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: fireball
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: BREAD
        output_amount: 16
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: WIND_CHARGE 
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: ENDER_PEARL
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: COBWEB
        output_amount: 16
  defenders:
    title: "Defender Shop"
    trades:
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: RED_WOOL
        output_amount: 64
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: END_STONE
        output_amount: 64
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: STONE_BRICK
        output_amount: 64
      - input_item: COPPER_INGOT
        input_amount: 8
        output_item: GOLDEN_APPLE
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 8
        output_item: instant_tnt
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: fireball
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: BREAD
        output_amount: 16
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: WIND_CHARGE
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 16
        output_item: ENDER_PEARL
        output_amount: 1
      - input_item: COPPER_INGOT
        input_amount: 4
        output_item: COBWEB
        output_amount: 16
