# CTF Plugin Configuration

game:
  world_name: "ctf_arena"
  world_type: NORMAL
  world_seed: ""
  attacker_spawn_radius: 50
  defender_spawn_radius: 20
  respawn_cooldown_seconds: 10
  flag_location_max_attempts: 100
  countdown_seconds: 5

kits:
  axe:
    team: ATTACKERS
    armor:
      helmet: LEATHER_HELMET
      chestplate: LEATHER_CHESTPLATE
      leggings: LEATHER_LEGGINGS
      boots: LEATHER_BOOTS
    items:
      - material: IRON_AXE
        amount: 1
      - material: STONE_PICKAXE
        amount: 1
      - material: STONE_SHOVEL
        amount: 1
      - custom_item: compass
        amount: 1
  sword:
    team: ATTACKERS
    armor:
      helmet: LEATHER_HELMET
      chestplate: LEATHER_CHESTPLATE
      leggings: LEATHER_LEGGINGS
      boots: LEATHER_BOOTS
    items:
      - material: IRON_SWORD
        amount: 1
      - material: SHIELD
        amount: 1
      - material: STONE_PICKAXE
        amount: 1
      - material: STONE_SHOVEL
        amount: 1
      - custom_item: compass
        amount: 1
  crossbow:
    team: ATTACKERS
    armor:
      helmet: LEATHER_HELMET
      chestplate: LEATHER_CHESTPLATE
      leggings: LEATHER_LEGGINGS
      boots: LEATHER_BOOTS
    items:
      - material: CROSSBOW
        amount: 1
      - material: STONE_PICKAXE
        amount: 1
      - material: STONE_SHOVEL
        amount: 1
      - material: ARROW
        amount: 16
      - custom_item: compass
        amount: 1

  knight:
    team: DEFENDERS
    armor:
      helmet: DIAMOND_HELMET
      chestplate: DIAMOND_CHESTPLATE
      leggings: DIAMOND_LEGGINGS
      boots: DIAMOND_BOOTS
    items:
      - material: DIAMOND_SWORD
        amount: 1
      - material: SHIELD
        amount: 1
      - material: IRON_AXE
        amount: 1

  archer:
    team: DEFENDERS
    armor:
      helmet: IRON_HELMET
      chestplate: IRON_CHESTPLATE
      leggings: IRON_LEGGINGS
      boots: IRON_BOOTS
    items:
      - material: IRON_SWORD
        amount: 1
      - material: BOW
        amount: 1
        enchantments:
          power: 1
      - material: ARROW
        amount: 64

  builder:
    team: DEFENDERS
    armor:
      helmet: CHAINMAIL_HELMET
      chestplate: CHAINMAIL_CHESTPLATE
      leggings: CHAINMAIL_LEGGINGS
      boots: CHAINMAIL_BOOTS
    items:
      - material: IRON_SWORD
        amount: 1
      - material: DIAMOND_PICKAXE
        amount: 1
      - material: STONE_BRICKS
        amount: 128
